# Site settings
title: "Matthew Ryan Camarena Resume"
description: "A resume using GitHub Pages for me - Matthew Camarena."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Matthew R. Camarena"
resume_title:                   "Computer Science Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "camarena.matthew@csu.fullerton.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(909) 702 0085"
resume_contact_address:         "2557 S Phoenix Pl, Ontario CA"

resume_header_contact_info:     "2557 S Phoenix Pl, Ontario CA • (909) 702 0085 • camarena.matthew@csu.fullerton.edu"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a computer science student pursuing a Bachelors Degree. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/MatthewCamarena"
  resume_twitter_url:           "http://twitter.com/mrcamarena"
  
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/MatthewCamarena"
  # resume_instagram_url:         "insert your Instagram URL here"
  

resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
